[package]
name = "i2c-amps"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-hal = "0.2.7"
linux-embedded-hal = "0.3.2"
rppal = "0.14.1"
plotters = "0.3"
rustfft = "6.1"
num-complex = "0.4"
clap = { version = "4.4", features = ["derive"] }
chrono = "0.4" 